version: "3.1"
services:
  api:
    build:
      context: .
      dockerfile: DockerfileApi
    restart: always
    expose:
      - 80
    networks:
      - reto-network

  consola:
    build:
      context: .
      dockerfile: DockerfileConsola
    restart: always
    networks:
      - reto-network

  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - reto-network
networks:
  reto-network:
